language: go
go:
- tip
deploy:
  provider: heroku
  api_key:
    secure: AuvD/TWPtZbWx/bwNoFqY0KAb0fgH0rq2lZM0kS3jA3d1wUB147YJcDdu1aapKznXAPwMGyfaa37qQygME4+bxo01Zl2GDhzq9ZPZ3LirXaaYKPC8lMbPVhuASmTo15VmLT4hkd3TfLsSrE9veWP96LNcexpopaXqyIcNIBPVIUQ9YDVlljXog1vp53PR54XiqPQ38qW1aiY86uyPOXlI5EWHzGR9/tV4ek0KsRJ09fjiThffRrf4hV/fQ9CfLVIFthdgAsUjVBFKOW2VUy8GAw0j4Q2QXSx9FGl1IaO7rfDK0oeNrHuLQDrR3Req26jYn4LoQE5m4ofRHCYDtsdxwx/Oo4wAKMBKnA8du3TohsVnaq/vaOiQQ4AiSGO61UPoey8V5MJkvlzcRQHHtkYAGaUawc2stWbcTNlgej8Ybc5SYKIeGajtvauXMMSct10OrtGaTbnAaOc4xcVCOY3a+udDu/YXdR7JG1hphApalqRLjygJR81lbwR8aaFHO9iQ+SWOy59doMl5Ir27TRQY1ZfC6Mlg8VJ3rYWel2GisOfKce43CRNSBWSpKLW+rxwP+nJbHHXenctfUB6SImrIJpfdIeH0MK5jAMtZjgZof/REN7ecUDpjiTjJd5LAlQGY7m1sv/gSFj6fEPB7OVK+y0ky9UZcgUJTGM2HGZPY88=
  app: DevOpsHeroku
  on:
    repo: karthick-raja/DevOpsHeroku
